from Yui_GBot import DEV_USERS, SUDO_USERS, SUPPORT_USERS, OP_USERS, SAFE_USERS, telethn

IMMUNE_USERS = SUDO_USERS + SAFE_USERS + SUPPORT_USERS + OP_USERS + DEV_USERS

IMMUNE_USERS = (
    list(SUDO_USERS) + list(SAFE_USERS) + list(SUPPORT_USERS) + list(OP_USERS) + list(DEV_USERS)
)
